### ISSUE TITLE
Controle de sincronização não funciona para agente rascunho

### ISSUE THREAD

**Issue by daphnemartinsba** [mapasculturais/plugin-MapasNetwork#30]
Ao criar um cadastro (o agente é criado em rascunho) no ambiente do PA e do MS e tentar desmarcar o checkbox  "Sincronizar": 
![image](https://user-images.githubusercontent.com/75261677/140802750-23f46888-5c31-4e3d-bae0-d015b2b7b9b8.png)

Ocorre o seguinte erro: 
![image](https://user-images.githubusercontent.com/75261677/140802608-cf7cfc87-6d71-4211-8d02-d5f37b83176b.png)

Atenção! No ES dá certo.
![image](https://user-images.githubusercontent.com/75261677/140803845-37a40fc7-fa36-48f9-a3bf-340aab931a78.png)

**Comment by daphnemartinsba** [comment]
Log:

[08-Nov-2021 18:57:17] WARNING: [pool www] child 10297 said into stderr: "ErrorException: get_class() expects parameter 1 to be object, null given in /var/www/html/protected/application/lib/MapasCulturais/Exceptions/PermissionDenied.php:19"

[08-Nov-2021 18:57:17] WARNING: [pool www] child 10297 said into stderr: "Stack trace:"

[08-Nov-2021 18:57:17] WARNING: [pool www] child 10297 said into stderr: "#0 [internal function]: Slim\Slim::handleErrors(2, 'get_class() exp...', '/var/www/html/p...', 19, Array)"

[08-Nov-2021 18:57:17] WARNING: [pool www] child 10297 said into stderr: "#1 /var/www/html/protected/application/lib/MapasCulturais/Exceptions/PermissionDenied.php(19): get_class(NULL)"

[08-Nov-2021 18:57:17] WARNING: [pool www] child 10297 said into stderr: "#2 /var/www/html/protected/application/plugins/MapasNetwork/Controllers/Node.php(844): MapasCulturais\Exceptions\PermissionDenied->__construct(Object(MapasCulturais\Entities\User), NULL, 'control synchro...')"

[08-Nov-2021 18:57:17] WARNING: [pool www] child 10297 said into stderr: "#3 /var/www/html/protected/application/lib/MapasCulturais/Controller.php(321): MapasNetwork\Controllers\Node->POST_syncControl()"

[08-Nov-2021 18:57:17] WARNING: [pool www] child 10297 said into stderr: "#4 /var/www/html/protected/application/lib/MapasCulturais/RoutesManager.php(168): MapasCulturais\Controller->callAction('POST', 'syncControl', Array)"

[08-Nov-2021 18:57:17] WARNING: [pool www] child 10297 said into stderr: "#5 /var/www/html/protected/application/lib/MapasCulturais/RoutesManager.php(106): MapasCulturais\RoutesManager->callAction(Object(MapasNetwork\Controllers\Node), 'syncControl', Array, false)"

[08-Nov-2021 18:57:17] WARNING: [pool www] child 10297 said into stderr: "#6 [internal function]: MapasCulturais\RoutesManager->MapasCulturais\{closure}(Array)"

[08-Nov-2021 18:57:17] WARNING: [pool www] child 10297 said into stderr: "#7 /var/www/html/protected/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)"

[08-Nov-2021 18:57:17] WARNING: [pool www] child 10297 said into stderr: "#8 /var/www/html/protected/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()"

[08-Nov-2021 18:57:17] WARNING: [pool www] child 10297 said into stderr: "#9 /var/www/html/protected/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()"

[08-Nov-2021 18:57:17] WARNING: [pool www] child 10297 said into stderr: "#10 /var/www/html/protected/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()"

[08-Nov-2021 18:57:17] WARNING: [pool www] child 10297 said into stderr: "#11 /var/www/html/protected/vendor/slim/slim/Slim/Slim.php(1300): Slim\Middleware\MethodOverride->call()"

[08-Nov-2021 18:57:17] WARNING: [pool www] child 10297 said into stderr: "#12 /var/www/html/protected/application/lib/MapasCulturais/App.php(588): Slim\Slim->run()"

[08-Nov-2021 18:57:17] WARNING: [pool www] child 10297 said into stderr: "#13 /var/www/html/index.php(4): MapasCulturais\App->run()"

[08-Nov-2021 18:57:17] WARNING: [pool www] child 10297 said into stderr: "#14 {main}"

10.42.2.204 -  08/Nov/2021:18:57:17 +0000 "POST /index.php" 500

**Comment by Uragawa** [comment]
Atualmente não está reproduzindo a issue.
